import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "animate.css";
import { MantineProvider } from "@mantine/core";
import Navbar from "@/components/Navbar";
import ThemeChanger from "@/components/ThemeChanger";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased bg-gradient-to-r from-slate-900 to-neutral-900`}
      >
        <MantineProvider>
          <Navbar />
          <ThemeChanger />
          <main className="mt-20 lg:mt-14">{children}</main>
          <Footer />
        </MantineProvider>
      </body>
    </html>
  );
}
